AWSTemplateFormatVersion: "2010-09-09"
Description: "learning-kms"

Resources:
  KMSKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: !Sub "${AWS::StackName} KMS Key"
      Enabled: true
      EnableKeyRotation: false
      KeySpec: "SYMMETRIC_DEFAULT"
      KeyUsage: "ENCRYPT_DECRYPT"
  KMSKeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}"
      TargetKeyId: !Ref KMSKey

Outputs:
  KMSKeyArn:
    Description: "KMS Key Arn"
    Value: !GetAtt KMSKey.Arn
